#
# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
#
# Sample docker-compose for OpenIG

# Important note: The Docker container that you deploy must
# be able to reach any network IPs that your OpenIG config
# might reference. This also included DNS resolution.
# This might be different than what your host (e.g. MacOS) can reach.
# This is where a Kubernetes deployment is going to make this easier
# as it can wire up DNS and service reachability.
# You can add host: entries below for Docker compose that will result
# in /etc/host entries being created in the Docker image. As above,
# these IP addresses must be resolvable from the Docker image itself.
openig:
  build: .
  # 8080 is often used - so lets remap this to something else.
  ports:
   - "5080:8080"
  # Below is an example of mounting a volume so you can do
  # Local development.
  # Note on MacOS / Docker: you need to setup Docker Machine so it
  # shares and mounts your home directory onto the Docker Machine.
  # This should be done for you when you install Docker machine.
  # If you attempt to use a relative mount (not /Users/xxx, but xxx),
  # the volume is relative to the boot2docker VM, not your Mac.
  volumes:
    - ./sample-config:/var/openig
