node {
        //Checkout
        stage ("Checkout") {
              checkout scm
              gitCommit = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
              // short SHA, possibly better for chat notifications, etc.
              shortCommit = gitCommit.take(7)
              env.GIT_COMMIT = shortCommit
     }
        stage ("Build") {
               withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'tnstamp',
               userNameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                     sshagent(['TStampGit']) {
                                sh "./build.sh"
                     }
               }
     }
}
