#Example of how to run OpenDJ with a custom configuration
# test with docker-compose up --force-recreate
#
# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
opendj:
  build: .
  ports:
   - "389:389"
  environment:
    # Uncomment this to bootstrap to the CTS sample
    #BOOTSTRAP: /opt/opendj/bootstrap/cts/setup.sh
    SOMEVAR: "keep compose happy"
  volumes:
# uncomment to create a persistent directory
#    - /tmp/opendj:/opt/opendj/data
  # This mounts a secret volume for the password and for key/trust stores
    - ./secrets:/var/secrets/opendj